name: Validation Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**/*.php'

jobs:
  lint-and-test:
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.0']
    runs-on: ${{ matrix.operating-system }}
    if: github.event.pull_request.draft == false
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display PHP information
        run: |
          php -v
          php -m
          composer --version
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run composer validate
        run: composer validate

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --no-scripts --prefer-dist --ansi

      - name: Run phpcstd
        run: vendor/bin/phpcstd --ci --ansi

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run Unit tests
        run: composer test --ansi
